### ISSUE TITLE
is usage example out of date with pixijs 6.1.3?

### ISSUE THREAD

**Issue by julapy** [pixijs/batch#12]
hi, ive been trying to get your example working with the latest pixijs 6.1.3 but it seems to me that the pixijs api and internals have since changed... can you confirm if your package is out of date?

**Comment by julapy** [comment]
also if you can tell me the last version of pixijs that you had this working with, perhaps i can roll back.

**Comment by julapy** [comment]
ive rolled back to pixijs 6.0.0 which the lowest dependency version for your package but still getting issues.
to be more specific, i get a crash on `setObjectRenderer` where it complains it is not a function.
```
    renderer.setObjectRenderer(renderer.plugins["ExampleRenderer"]);
    renderer.plugins["ExampleRenderer"].render(this);
```

**Comment by ShukantPal** [comment]
@julapy Did you move from PixiJS 4 to 6? This would not have worked in 5 either.

It's renderer.batch.setObjectRenderer (you're missing the "batch" part?)

**Comment by julapy** [comment]
hey @ShukantPal ive only been using pixijs 6
i did try adding `renderer.batch.setObjectRenderer` previously but then got some other shader errors.
what version of pixi is your example documented on github intended for?

**Comment by ShukantPal** [comment]
It was written when PixiJS 5 came out. But it should work with 6. There may be a mistake in the shader if it isn't compiling.

**Comment by julapy** [comment]
im simply copy and pasting your example and getting those errors.
do you happen to have a working example for pixijs 6 so i can compare with how ive laid it out?

**Comment by julapy** [comment]
i also ran the example with pixijs 5.3.11 but also that didn't work.
which version of pixijs 5 did you write this package for?
cheers.
